<form class="form-signin" role="form" action="<?=$base_url?>/auth/signin" method="post">
    <input type="hidden" name="confirm" value="ok" />

    <h2 class="form-signin-heading"><?=l('authorization')?></h2>

    <?php if( !empty($error) ): ?>
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong><?=ufl('error')?>!</strong> <?=$error?>
    </div>
    <?php endif; ?>
    
    <input type="email" name="form[email]" class="form-control" placeholder="<?=ufl('user')?>" required autofocus />
    <input type="password" name="form[password]" class="form-control" placeholder="<?=ufl('password')?>" required />

    <br />
    
    <button class="btn btn-lg btn-primary btn-block" type="submit">
        <span class="glyphicon glyphicon-log-in"></span> 
        <?=ufl('enter')?>
    </button>
</form>
