<div class="page-header">
  <h3><span class="glyphicon glyphicon-user"></span> Редактирование пользователя</h3>
</div>

<?php if( !empty($usersave) ): ?>
<div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Отлично!</strong> Данные пользователя успешно изменены.
</div>
<?php endif; ?>

<?php if( !empty($errors) ): ?>
<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Внимание!</strong> При заполнении формы были допущены ошибки.<br />
    <ul>
    <?php foreach($errors as $key=>$val): ?>
        <?php if( array_count($val) ): ?>
        <li><?=$key?>:
            <ul>
            <?php foreach($val as $error): ?>
                <li><?=$error?></li>
            <?php endforeach; ?>
            </ul>
        </li>
        <?php endif; ?>
    <?php endforeach;?>
    </ul>
</div>
<?php endif; ?>                        

<div class="col-xs-10">
    <form role="form" class="form-horizontal col-xs-10" action="<?=$base_url?>/users/add" method="post">
        <input type="hidden" name="confirm" value="ok" />

        <div class="form-group<?php if( !empty($errors['email'])) echo ' has-error'; ?>">
            <label for="user-email" class="control-label col-xs-4">Email:</label>

            <div class="col-xs-8">
                <input type="email" name="form[email]" class="form-control" id="user-email" value="<?=(isset($form['email']) ? $form['email'] : '')?>" maxlength="255" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['nicname'])) echo ' has-error'; ?>">
            <label for="user-nicname" class="control-label col-xs-4"><?=ufl('nickname')?>:</label>

            <div class="col-xs-8">
                <input type="text" name="form[nicname]" class="form-control" id="user-nicname" value="<?=(isset($form['nicname']) ? $form['nicname'] : '')?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['first_name'])) echo ' has-error'; ?>">
            <label for="user-first-name" class="control-label col-xs-4">
                <?=ufl('first_name')?>:
            </label>

            <div class="col-xs-8">
                <input type="text" name="form[first_name]" class="form-control" id="user-first-name" value="<?=( isset($form['first_name']) ? $form['first_name'] : '' )?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['middle_name'])) echo ' has-error'; ?>">
            <label for="user-middle-name" class="control-label col-xs-4"><?=ufl('middle_name')?>:</label>

            <div class="col-xs-8">
                <input type="text" name="form[middle_name]" class="form-control" id="user-middle-name" value="<?=( isset($form['middle_name']) ? $form['middle_name'] : '' )?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['last_name'])) echo ' has-error'; ?>">
            <label for="user-last-name" class="control-label col-xs-4"><?=ufl('last_name')?>:</label>

            <div class="col-xs-8">
                <input type="text" name="form[last_name]" class="form-control" id="user-last-name" value="<?=( isset($form['last_name']) ? $form['last_name'] : '' )?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['birthday'])) echo ' has-error'; ?>">
            <label for="user-birthday" class="control-label col-xs-4"><?=ufl('birthday')?></label>

            <div class="col-xs-8">
                <input type="text" 
                       name="form[birthday]" 
                       id="user-birthday" 
                       class="form-control"
                       data-date="<?=(!empty($form['birthday']) ? wasp_date_format($form['birthday'], 'd.m.Y') : date('d.m.Y'))?>" 
                       data-date-format="dd.mm.yyyy"
                       value="<?=( !empty($form['birthday']) ? wasp_date_format($form['birthday'], 'd.m.Y') : date('d.m.Y') )?>" 
                       maxlength="32"
                       readonly="readonly" />
            </div>
        </div>
        
        <div class="form-group<?php if( !empty($errors['gender'])) echo ' has-error'; ?>">
            <label for="user-gender" class="control-label col-xs-4"><?=ufl('gender')?>:</label>

            <div class="col-xs-8">
                <select name="form[gender]" class="form-control" id="user-gender">
                    <option value="MALE"<?=(('MALE' == $form['gender']) ? ' selected="selected"' : '')?>><?=ufl('male')?></option>
                    <option value="FEMALE"<?=(('FEMALE' == $form['gender']) ? ' selected="selected"' : '')?>><?=ufl('female')?></option>
                    <option value="OTHER"<?=(('OTHER' == $form['gender']) ? ' selected="selected"' : '')?>><?=ufl('other')?></option>
                </select>
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['type'])) echo ' has-error'; ?>">
            <label for="user-group" class="control-label col-xs-4"><?=ufl('group')?>:</label>

            <div class="col-xs-8">
                <select name="form[group_id]" class="form-control" id="user-group">
                <?php foreach($groups as $key=>$val): ?>
                    <?php if( $authUser->group->level > $val->level ): ?>
                    <option value="<?=$key?>"<?=(($key == $form['group_id']) ? ' selected="selected"' : '')?>><?=$val->name?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="user-blocked" class="control-label col-xs-4"><?=ufl('block')?>:</label>

            <div class="col-xs-8">
                <select name="form[blocked]" class="form-control" id="user-blocked">
                    <option value="0"<?php if( $form['blocked'] == 0 ) echo ' selected="selected"'; ?>>Разблокирован</option>
                    <option value="1"<?php if( $form['blocked'] == 1 ) echo ' selected="selected"'; ?>>Заблокирован</option>
                </select>
            </div>
        </div>
        
        <div class="form-group<?php if( !empty($errors['password'])) echo ' has-error'; ?>">
            <label for="user-passwd1" class="control-label col-xs-4"><?=ufl('password')?>:</label>

            <div class="col-xs-8">
                <input type="password" name="form[passwd1]" class="form-control" id="user-passwd1" maxlength="16" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['password'])) echo ' has-error'; ?>">
            <label for="user-passwd2" class="control-label col-xs-4">Повторить пароль:</label>

            <div class="col-xs-8">
                <input type="password" name="form[passwd2]" class="form-control" id="user-passwd2" maxlength="16" />
            </div>
        </div>

        <div class="col-xs-10"></div>
        <div class="col-xs-2">
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-floppy-save"></span>&nbsp;
                <?=ufl('save')?>
            </button>
        </div>
        
    </form>
</div>
<script type="text/javascript">
$(function(){
    $('#user-birthday').datepicker();
});
</script>