<div class="page-header">
  <h3><span class="glyphicon glyphicon-list-alt"></span> Список пользователей</h3>
</div>

<div class="col-xs-12">
    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 5%;"> # </th>        
                <th style="width: 45%;"> Email </th>        
                <th style="width: 15%;"> <?=ufl('group')?> </th>        
                <th style="width: 25%;"> Last time </th>        
                <th style="width: 10%;"> --- </th>        
            </tr>
        </thead>
        
        <tbody>
        <?php foreach($users as $key=>$val): ?>
            <tr>
                <td style="width: 5%;"><?=$key?></td>
                <td style="width: 45%;"><?=$val->emails()->first()->value?></td>
                <td style="width: 15%;"><?=$val->group->name?></td>
                <td style="width: 25%;"><?=((!empty($val->session->stamp)) ? date('d.m.Y H:i:s', $val->session->stamp) : '')?></td>
                <td style="width: 10%;">
                    <?php if( $val->group->level < $authUser->group->level || $authLib->isAdmin() || $authUser->id == $val->id ): ?>
                    <span class="glyphicon glyphicon-pencil" title="<?=ufl('edit')?>" style="cursor: pointer;" onclick="wasp.redirect(wasp.url+'/users/edit/id/<?=$val->id?>')"></span>
                    &nbsp;
                        <?php if( $authUser->id != $val->id ): ?>
                    <span class="glyphicon glyphicon-remove" title="<?=ufl('delete')?>" style="cursor: pointer;" onclick="wasp.fn.user_delete(<?=$key?>, '<?=$val->email()->value?>')"></span>
                        <?php endif; ?>
                    <?php endif;  ?>
                </td>
            </tr>
        <?php endforeach; ?>    
        </tbody>
    </table>
</div>    

<script type="text/javascript">
wasp.fn.user_delete = function(id, email) {
    if( typeof(id) == 'undefined' || typeof(id) == 'email' || id == '' || email == '' ) {
        return false;
    }
    
    wasp.confirm('Вы действительно желаете удалить пользователя ' + email + '?', 'Удалить пользователя?', function(){
        wasp.ajax('<?=$base_url?>/?do=users-delete', function(r){
            if( r == 'success' ) {
                wasp.redirect('<?=$base_url?>/?do=users');
            } else {
                wasp.message('Удаление не удалось. Что-то пошло не так.');
            }
        }, {
            'id': id
        });
    });
}
</script>    
    