<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="generator" content="<?=$framework?>">
        <meta name="author" content="Tishchenko Alexander">
        <link rel="shortcut icon" href="<?=$theme_url?>/favicon.ico">

        <title>Wasp &raquo; <?=l('authorization')?></title>

        <script type="text/javascript" src="<?=$js_url?>/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="<?=$base_url?>/js"></script>

        <!-- Bootstrap core CSS -->
        <!--<link href="<?=$css_url?>/bootstrap.min.css" rel="stylesheet">-->
        <link href="<?=$css_url?>/bootstrap.spacelab.min.css" rel="stylesheet" />
        <link href="<?=$css_url?>/bootstrap-theme.min.css" rel="stylesheet" />
        <link href="<?=$css_url?>/font-awesome.min.css" rel="stylesheet" />

        <!-- Custom styles for this template -->
        <link href="<?=$css_url?>/signin.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]>
        <script src="<?=$js_url?>/ie8-responsive-file-warning.js"></script>
        <![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="<?=$js_url?>/html5shiv.js"></script>
        <script src="<?=$js_url?>/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="container">
        <?=$content?>
        </div> <!-- /container -->

        <script type="text/javascript" src="<?=$js_url?>/bootstrap.min.js"></script>
    </body>
</html>