<div class="page-header">
  <h3><span class="glyphicon glyphicon-user"></span> <?=l('user_profile')?></h3>
</div>

<?php if( !empty($usersave) ): ?>
<div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Отлично!</strong> Данные пользователя успешно изменены.
</div>
<?php endif; ?>

<?php if( !empty($errors) ): ?>
<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Внимание!</strong> При заполнении формы были допущены ошибки.<br />
    <ul>
    <?php foreach($errors as $key=>$val): ?>
        <?php if( array_count($val) ): ?>
        <li><?=$key?>:
            <ul>
            <?php foreach($val as $error): ?>
                <li><?=$error?></li>
            <?php endforeach; ?>
            </ul>
        </li>
        <?php endif; ?>
    <?php endforeach;?>
    </ul>
</div>
<?php endif; ?>                        

<div class="col-xs-10">
    <form role="form" class="form-horizontal col-xs-10" action="<?=$base_url?>/profile" method="post">
        <input type="hidden" name="confirm" value="ok" />

        <div class="form-group<?php if( !empty($errors['nicname'])) echo ' has-error'; ?>">
            <label for="user-nicname" class="control-label col-xs-4"><?=ufl('nickname')?>:</label>

            <div class="col-xs-8">
                <input type="text" name="form[nicname]" class="form-control" id="user-nicname" value="<?=( (!empty($errors['nicname'])) ? escape($errors['nicname']) : $user->profile->nicname )?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['first_name'])) echo ' has-error'; ?>">
            <label for="user-first-name" class="control-label col-xs-4">
                <?=ufl('first_name')?>:
            </label>

            <div class="col-xs-8">
                <input type="text" name="form[first_name]" class="form-control" id="user-first-name" value="<?=( (!empty($errors['first_name'])) ? escape($errors['first_name']) : $user->profile->first_name )?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['middle_name'])) echo ' has-error'; ?>">
            <label for="user-middle-name" class="control-label col-xs-4"><?=ufl('middle_name')?>:</label>

            <div class="col-xs-8">
                <input type="text" name="form[middle_name]" class="form-control" id="user-middle-name" value="<?=( (!empty($errors['middle_name'])) ? escape($errors['middle_name']) : $user->profile->middle_name )?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['last_name'])) echo ' has-error'; ?>">
            <label for="user-last-name" class="control-label col-xs-4"><?=ufl('last_name')?>:</label>

            <div class="col-xs-8">
                <input type="text" name="form[last_name]" class="form-control" id="user-last-name" value="<?=( (!empty($errors['last_name'])) ? escape($errors['last_name']) : $user->profile->last_name )?>" maxlength="32" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['birthday'])) echo ' has-error'; ?>">
            <label for="user-birthday" class="control-label col-xs-4"><?=ufl('birthday')?></label>

            <div class="col-xs-8">
                <input type="text" 
                       name="form[birthday]" 
                       id="user-birthday" 
                       class="form-control"
                       data-date="<?=wasp_date_format($user->profile->birthday, 'd.m.Y')?>" 
                       data-date-format="dd.mm.yyyy"
                       value="<?=wasp_date_format($user->profile->birthday, 'd.m.Y')?>" 
                       maxlength="32"
                       readonly="readonly" />
            </div>
        </div>
        
        <div class="form-group<?php if( !empty($errors['gender'])) echo ' has-error'; ?>">
            <label for="user-gender" class="control-label col-xs-4"><?=ufl('gender')?>:</label>

            <div class="col-xs-8">
                <select name="form[gender]" class="form-control" id="user-gender">
                    <option value="MALE"<?=(('MALE' == $user->profile->gender) ? ' selected="selected"' : '')?>><?=ufl('male')?></option>
                    <option value="FEMALE"<?=(('FEMALE' == $user->profile->gender) ? ' selected="selected"' : '')?>><?=ufl('female')?></option>
                    <option value="OTHER"<?=(('OTHER' == $user->profile->gender) ? ' selected="selected"' : '')?>><?=ufl('other')?></option>
                </select>
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['password'])) echo ' has-error'; ?>">
            <label for="user-passwd1" class="control-label col-xs-4"><?=ufl('password')?>:</label>

            <div class="col-xs-8">
                <input type="password" name="form[passwd1]" class="form-control" id="user-passwd1" maxlength="16" />
            </div>
        </div>

        <div class="form-group<?php if( !empty($errors['password'])) echo ' has-error'; ?>">
            <label for="user-passwd2" class="control-label col-xs-4">Повторить пароль:</label>

            <div class="col-xs-8">
                <input type="password" name="form[passwd2]" class="form-control" id="user-passwd2" maxlength="16" />
            </div>
        </div>

        <div class="col-xs-10"></div>
        <div class="col-xs-2">
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-floppy-save"></span>&nbsp;
                <?=ufl('save')?>
            </button>
        </div>
        
    </form>
</div>
<script type="text/javascript">
$(function(){
    $('#user-birthday').datepicker();
});
</script>